require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe KitUniformsController do

  # This should return the minimal set of attributes required to create a valid
  # KitUniform. As you add validations to KitUniform, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "kit_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # KitUniformsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all kit_uniforms as @kit_uniforms" do
      kit_uniform = KitUniform.create! valid_attributes
      get :index, {}, valid_session
      assigns(:kit_uniforms).should eq([kit_uniform])
    end
  end

  describe "GET show" do
    it "assigns the requested kit_uniform as @kit_uniform" do
      kit_uniform = KitUniform.create! valid_attributes
      get :show, {:id => kit_uniform.to_param}, valid_session
      assigns(:kit_uniform).should eq(kit_uniform)
    end
  end

  describe "GET new" do
    it "assigns a new kit_uniform as @kit_uniform" do
      get :new, {}, valid_session
      assigns(:kit_uniform).should be_a_new(KitUniform)
    end
  end

  describe "GET edit" do
    it "assigns the requested kit_uniform as @kit_uniform" do
      kit_uniform = KitUniform.create! valid_attributes
      get :edit, {:id => kit_uniform.to_param}, valid_session
      assigns(:kit_uniform).should eq(kit_uniform)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new KitUniform" do
        expect {
          post :create, {:kit_uniform => valid_attributes}, valid_session
        }.to change(KitUniform, :count).by(1)
      end

      it "assigns a newly created kit_uniform as @kit_uniform" do
        post :create, {:kit_uniform => valid_attributes}, valid_session
        assigns(:kit_uniform).should be_a(KitUniform)
        assigns(:kit_uniform).should be_persisted
      end

      it "redirects to the created kit_uniform" do
        post :create, {:kit_uniform => valid_attributes}, valid_session
        response.should redirect_to(KitUniform.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved kit_uniform as @kit_uniform" do
        # Trigger the behavior that occurs when invalid params are submitted
        KitUniform.any_instance.stub(:save).and_return(false)
        post :create, {:kit_uniform => { "kit_id" => "invalid value" }}, valid_session
        assigns(:kit_uniform).should be_a_new(KitUniform)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        KitUniform.any_instance.stub(:save).and_return(false)
        post :create, {:kit_uniform => { "kit_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested kit_uniform" do
        kit_uniform = KitUniform.create! valid_attributes
        # Assuming there are no other kit_uniforms in the database, this
        # specifies that the KitUniform created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        KitUniform.any_instance.should_receive(:update).with({ "kit_id" => "1" })
        put :update, {:id => kit_uniform.to_param, :kit_uniform => { "kit_id" => "1" }}, valid_session
      end

      it "assigns the requested kit_uniform as @kit_uniform" do
        kit_uniform = KitUniform.create! valid_attributes
        put :update, {:id => kit_uniform.to_param, :kit_uniform => valid_attributes}, valid_session
        assigns(:kit_uniform).should eq(kit_uniform)
      end

      it "redirects to the kit_uniform" do
        kit_uniform = KitUniform.create! valid_attributes
        put :update, {:id => kit_uniform.to_param, :kit_uniform => valid_attributes}, valid_session
        response.should redirect_to(kit_uniform)
      end
    end

    describe "with invalid params" do
      it "assigns the kit_uniform as @kit_uniform" do
        kit_uniform = KitUniform.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        KitUniform.any_instance.stub(:save).and_return(false)
        put :update, {:id => kit_uniform.to_param, :kit_uniform => { "kit_id" => "invalid value" }}, valid_session
        assigns(:kit_uniform).should eq(kit_uniform)
      end

      it "re-renders the 'edit' template" do
        kit_uniform = KitUniform.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        KitUniform.any_instance.stub(:save).and_return(false)
        put :update, {:id => kit_uniform.to_param, :kit_uniform => { "kit_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested kit_uniform" do
      kit_uniform = KitUniform.create! valid_attributes
      expect {
        delete :destroy, {:id => kit_uniform.to_param}, valid_session
      }.to change(KitUniform, :count).by(-1)
    end

    it "redirects to the kit_uniforms list" do
      kit_uniform = KitUniform.create! valid_attributes
      delete :destroy, {:id => kit_uniform.to_param}, valid_session
      response.should redirect_to(kit_uniforms_url)
    end
  end

end
