require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe KitsController do

  # This should return the minimal set of attributes required to create a valid
  # Kit. As you add validations to Kit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "code" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # KitsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all kits as @kits" do
      kit = Kit.create! valid_attributes
      get :index, {}, valid_session
      assigns(:kits).should eq([kit])
    end
  end

  describe "GET show" do
    it "assigns the requested kit as @kit" do
      kit = Kit.create! valid_attributes
      get :show, {:id => kit.to_param}, valid_session
      assigns(:kit).should eq(kit)
    end
  end

  describe "GET new" do
    it "assigns a new kit as @kit" do
      get :new, {}, valid_session
      assigns(:kit).should be_a_new(Kit)
    end
  end

  describe "GET edit" do
    it "assigns the requested kit as @kit" do
      kit = Kit.create! valid_attributes
      get :edit, {:id => kit.to_param}, valid_session
      assigns(:kit).should eq(kit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Kit" do
        expect {
          post :create, {:kit => valid_attributes}, valid_session
        }.to change(Kit, :count).by(1)
      end

      it "assigns a newly created kit as @kit" do
        post :create, {:kit => valid_attributes}, valid_session
        assigns(:kit).should be_a(Kit)
        assigns(:kit).should be_persisted
      end

      it "redirects to the created kit" do
        post :create, {:kit => valid_attributes}, valid_session
        response.should redirect_to(Kit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved kit as @kit" do
        # Trigger the behavior that occurs when invalid params are submitted
        Kit.any_instance.stub(:save).and_return(false)
        post :create, {:kit => { "code" => "invalid value" }}, valid_session
        assigns(:kit).should be_a_new(Kit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Kit.any_instance.stub(:save).and_return(false)
        post :create, {:kit => { "code" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested kit" do
        kit = Kit.create! valid_attributes
        # Assuming there are no other kits in the database, this
        # specifies that the Kit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Kit.any_instance.should_receive(:update).with({ "code" => "MyString" })
        put :update, {:id => kit.to_param, :kit => { "code" => "MyString" }}, valid_session
      end

      it "assigns the requested kit as @kit" do
        kit = Kit.create! valid_attributes
        put :update, {:id => kit.to_param, :kit => valid_attributes}, valid_session
        assigns(:kit).should eq(kit)
      end

      it "redirects to the kit" do
        kit = Kit.create! valid_attributes
        put :update, {:id => kit.to_param, :kit => valid_attributes}, valid_session
        response.should redirect_to(kit)
      end
    end

    describe "with invalid params" do
      it "assigns the kit as @kit" do
        kit = Kit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Kit.any_instance.stub(:save).and_return(false)
        put :update, {:id => kit.to_param, :kit => { "code" => "invalid value" }}, valid_session
        assigns(:kit).should eq(kit)
      end

      it "re-renders the 'edit' template" do
        kit = Kit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Kit.any_instance.stub(:save).and_return(false)
        put :update, {:id => kit.to_param, :kit => { "code" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested kit" do
      kit = Kit.create! valid_attributes
      expect {
        delete :destroy, {:id => kit.to_param}, valid_session
      }.to change(Kit, :count).by(-1)
    end

    it "redirects to the kits list" do
      kit = Kit.create! valid_attributes
      delete :destroy, {:id => kit.to_param}, valid_session
      response.should redirect_to(kits_url)
    end
  end

end
