require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StaffMeasurementsController do

  # This should return the minimal set of attributes required to create a valid
  # StaffMeasurement. As you add validations to StaffMeasurement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "staff_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StaffMeasurementsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all staff_measurements as @staff_measurements" do
      staff_measurement = StaffMeasurement.create! valid_attributes
      get :index, {}, valid_session
      assigns(:staff_measurements).should eq([staff_measurement])
    end
  end

  describe "GET show" do
    it "assigns the requested staff_measurement as @staff_measurement" do
      staff_measurement = StaffMeasurement.create! valid_attributes
      get :show, {:id => staff_measurement.to_param}, valid_session
      assigns(:staff_measurement).should eq(staff_measurement)
    end
  end

  describe "GET new" do
    it "assigns a new staff_measurement as @staff_measurement" do
      get :new, {}, valid_session
      assigns(:staff_measurement).should be_a_new(StaffMeasurement)
    end
  end

  describe "GET edit" do
    it "assigns the requested staff_measurement as @staff_measurement" do
      staff_measurement = StaffMeasurement.create! valid_attributes
      get :edit, {:id => staff_measurement.to_param}, valid_session
      assigns(:staff_measurement).should eq(staff_measurement)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StaffMeasurement" do
        expect {
          post :create, {:staff_measurement => valid_attributes}, valid_session
        }.to change(StaffMeasurement, :count).by(1)
      end

      it "assigns a newly created staff_measurement as @staff_measurement" do
        post :create, {:staff_measurement => valid_attributes}, valid_session
        assigns(:staff_measurement).should be_a(StaffMeasurement)
        assigns(:staff_measurement).should be_persisted
      end

      it "redirects to the created staff_measurement" do
        post :create, {:staff_measurement => valid_attributes}, valid_session
        response.should redirect_to(StaffMeasurement.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved staff_measurement as @staff_measurement" do
        # Trigger the behavior that occurs when invalid params are submitted
        StaffMeasurement.any_instance.stub(:save).and_return(false)
        post :create, {:staff_measurement => { "staff_id" => "invalid value" }}, valid_session
        assigns(:staff_measurement).should be_a_new(StaffMeasurement)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StaffMeasurement.any_instance.stub(:save).and_return(false)
        post :create, {:staff_measurement => { "staff_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested staff_measurement" do
        staff_measurement = StaffMeasurement.create! valid_attributes
        # Assuming there are no other staff_measurements in the database, this
        # specifies that the StaffMeasurement created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StaffMeasurement.any_instance.should_receive(:update).with({ "staff_id" => "1" })
        put :update, {:id => staff_measurement.to_param, :staff_measurement => { "staff_id" => "1" }}, valid_session
      end

      it "assigns the requested staff_measurement as @staff_measurement" do
        staff_measurement = StaffMeasurement.create! valid_attributes
        put :update, {:id => staff_measurement.to_param, :staff_measurement => valid_attributes}, valid_session
        assigns(:staff_measurement).should eq(staff_measurement)
      end

      it "redirects to the staff_measurement" do
        staff_measurement = StaffMeasurement.create! valid_attributes
        put :update, {:id => staff_measurement.to_param, :staff_measurement => valid_attributes}, valid_session
        response.should redirect_to(staff_measurement)
      end
    end

    describe "with invalid params" do
      it "assigns the staff_measurement as @staff_measurement" do
        staff_measurement = StaffMeasurement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StaffMeasurement.any_instance.stub(:save).and_return(false)
        put :update, {:id => staff_measurement.to_param, :staff_measurement => { "staff_id" => "invalid value" }}, valid_session
        assigns(:staff_measurement).should eq(staff_measurement)
      end

      it "re-renders the 'edit' template" do
        staff_measurement = StaffMeasurement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StaffMeasurement.any_instance.stub(:save).and_return(false)
        put :update, {:id => staff_measurement.to_param, :staff_measurement => { "staff_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested staff_measurement" do
      staff_measurement = StaffMeasurement.create! valid_attributes
      expect {
        delete :destroy, {:id => staff_measurement.to_param}, valid_session
      }.to change(StaffMeasurement, :count).by(-1)
    end

    it "redirects to the staff_measurements list" do
      staff_measurement = StaffMeasurement.create! valid_attributes
      delete :destroy, {:id => staff_measurement.to_param}, valid_session
      response.should redirect_to(staff_measurements_url)
    end
  end

end
