require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StockOrdersController do

  # This should return the minimal set of attributes required to create a valid
  # StockOrder. As you add validations to StockOrder, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "stock_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StockOrdersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all stock_orders as @stock_orders" do
      stock_order = StockOrder.create! valid_attributes
      get :index, {}, valid_session
      assigns(:stock_orders).should eq([stock_order])
    end
  end

  describe "GET show" do
    it "assigns the requested stock_order as @stock_order" do
      stock_order = StockOrder.create! valid_attributes
      get :show, {:id => stock_order.to_param}, valid_session
      assigns(:stock_order).should eq(stock_order)
    end
  end

  describe "GET new" do
    it "assigns a new stock_order as @stock_order" do
      get :new, {}, valid_session
      assigns(:stock_order).should be_a_new(StockOrder)
    end
  end

  describe "GET edit" do
    it "assigns the requested stock_order as @stock_order" do
      stock_order = StockOrder.create! valid_attributes
      get :edit, {:id => stock_order.to_param}, valid_session
      assigns(:stock_order).should eq(stock_order)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StockOrder" do
        expect {
          post :create, {:stock_order => valid_attributes}, valid_session
        }.to change(StockOrder, :count).by(1)
      end

      it "assigns a newly created stock_order as @stock_order" do
        post :create, {:stock_order => valid_attributes}, valid_session
        assigns(:stock_order).should be_a(StockOrder)
        assigns(:stock_order).should be_persisted
      end

      it "redirects to the created stock_order" do
        post :create, {:stock_order => valid_attributes}, valid_session
        response.should redirect_to(StockOrder.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved stock_order as @stock_order" do
        # Trigger the behavior that occurs when invalid params are submitted
        StockOrder.any_instance.stub(:save).and_return(false)
        post :create, {:stock_order => { "stock_id" => "invalid value" }}, valid_session
        assigns(:stock_order).should be_a_new(StockOrder)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StockOrder.any_instance.stub(:save).and_return(false)
        post :create, {:stock_order => { "stock_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested stock_order" do
        stock_order = StockOrder.create! valid_attributes
        # Assuming there are no other stock_orders in the database, this
        # specifies that the StockOrder created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StockOrder.any_instance.should_receive(:update).with({ "stock_id" => "1" })
        put :update, {:id => stock_order.to_param, :stock_order => { "stock_id" => "1" }}, valid_session
      end

      it "assigns the requested stock_order as @stock_order" do
        stock_order = StockOrder.create! valid_attributes
        put :update, {:id => stock_order.to_param, :stock_order => valid_attributes}, valid_session
        assigns(:stock_order).should eq(stock_order)
      end

      it "redirects to the stock_order" do
        stock_order = StockOrder.create! valid_attributes
        put :update, {:id => stock_order.to_param, :stock_order => valid_attributes}, valid_session
        response.should redirect_to(stock_order)
      end
    end

    describe "with invalid params" do
      it "assigns the stock_order as @stock_order" do
        stock_order = StockOrder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StockOrder.any_instance.stub(:save).and_return(false)
        put :update, {:id => stock_order.to_param, :stock_order => { "stock_id" => "invalid value" }}, valid_session
        assigns(:stock_order).should eq(stock_order)
      end

      it "re-renders the 'edit' template" do
        stock_order = StockOrder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StockOrder.any_instance.stub(:save).and_return(false)
        put :update, {:id => stock_order.to_param, :stock_order => { "stock_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested stock_order" do
      stock_order = StockOrder.create! valid_attributes
      expect {
        delete :destroy, {:id => stock_order.to_param}, valid_session
      }.to change(StockOrder, :count).by(-1)
    end

    it "redirects to the stock_orders list" do
      stock_order = StockOrder.create! valid_attributes
      delete :destroy, {:id => stock_order.to_param}, valid_session
      response.should redirect_to(stock_orders_url)
    end
  end

end
